// var web3 = new Web3();
// web3.setProvider(new web3.providers.HttpProvider());

// var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));

if (typeof web3 !== 'undefined') {
  	web3 = new Web3(web3.currentProvider);
} else {
  // set the provider you want from Web3.providers
  web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));

  // web3 = new Web3(new Web3.providers.HttpProvider("https://ropsten.infura.io/8BhEF9jhn86dgZMScxjU"));

	// var web3 = new Web3();
	// web3.setProvider(new web3.providers.HttpProvider());
}

// web3.eth.defaultAccount = web3.eth.accounts[0];
// var balance = web3.eth.getBalance(web3.eth.accounts[0]);

var getBalance = () => {
	console.log(web3);
	console.log((web3.eth.getBalance("0x46c23ae540b952456b7c56927d87a6625508bbee").toNumber()/1E18).toFixed(8));
}

/**
* wallets list formation with addres and balance data
*/
var wallets = [];
web3.eth.accounts.forEach((el) => {
	wallets.push({
		address: el,
		balance: (web3.eth.getBalance(el).toNumber()/1E18).toFixed(8)
	})
});

/**
* get information about transaction 
* !!! ADDRESSES NOT CORRECT !!! GET RIGHT ADDRESSES FROM NEW RECEIVED WALLETS GENERATED BY NEW  testrpc  !!!
*/
var getTransactionObject = () => {
	return({
		from: "0x69ba9000b98544ec863f6a2c2dfaac9f10afb62f",
		to: "0x46c23ae540b952456b7c56927d87a6625508bbee",
		value: 10000000000000000000,
		gas: 1000000,
		gasPrice: web3.eth.gasPrice
	});
};

var sendTransaction = () => {
	console.log(web3.eth.getTransaction(web3.eth.sendTransaction(getTransactionObject())));
	console.log(web3.eth.sendTransaction(getTransactionObject()));
};


/**
* get transaction for addres from your network
*/
var getTransactions = () => {
	console.log("getTransactions");
	console.log(web3.eth.getTransactionCount("0x46c23ae540b952456b7c56927d87a6625508bbee"));

	web3.eth.filter({
	  	address: "0x0697F258FE4B0Fc4998c5CC1A04E5099b3423da2",
	  	from: 0,
	  	to: 'latest'
	}).get(function (err, result) {
		console.log(result);
	})

}



/** 
*  ANGULAR PART - ADDIND DATA TO VIEW (INDEX.HTML)
*/
var app = angular.module("web3Test", []);

app.controller("myCtrl", function($scope) {
    $scope.wallets = wallets;
    $scope.getBalance = getBalance;
    $scope.sendTransaction = sendTransaction;
    $scope.getTransactions = getTransactions;
});

